# More about this file:
# https://clangd.llvm.org/config.html
#
# To verify clangd is actually picking-up this file:
#
# $ clangd --log=verbose
#
Hover:
  ShowAKA: Yes
Diagnostics:
  ClangTidy:
    # List of checks: https://clang.llvm.org/extra/clang-tidy/checks/list.html
    Add:
      - bugprone-*
      - cppcoreguidelines-*
      - modernize-*
      - performance-*
      - portability-*
      - readability-*
      - misc-*
    Remove:
      - readability-identifier-length
      - modernize-use-trailing-return-type
  # Run checks unless they're known to be slow. (Default: Strict)
  FastCheckFilter: Loose
  UnusedIncludes: Strict
  # This is just too noisy.
  # MissingIncludes: Strict
InlayHints:
  BlockEnd: true
  Designators: true
  Enabled: true
  ParameterNames: true
  DeducedTypes: true
  DefaultArguments: true
  TypeNameLimit: 24
Documentation:
  CommentFormat: Doxygen
CompileFlags:
  Add: [ -Wmismatched-tags, -Wconversion ]
