# More about this file:
# https://clangd.llvm.org/config.html
Hover:
  ShowAKA: Yes
Diagnostics:
  ClangTidy:
    Add:
      - bugprone-*
      - cppcoreguidelines-*
      - modernize-*
      - performance-*
      - portability-*
      - readability-*
    Remove:
      - readability-identifier-length
      - modernize-use-trailing-return-type
  UnusedIncludes: Strict
  # This is just too noisy.
  # MissingIncludes: Strict
InlayHints:
  BlockEnd: true
  Designators: true
  Enabled: true
  ParameterNames: true
  DeducedTypes: true
  DefaultArguments: true
  TypeNameLimit: 24
Documentation:
  CommentFormat: Doxygen
CompileFlags:
  Add: [ -Wmismatched-tags, -Wconversion ]
